before:
  hooks:
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=1
  - dir: .
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - "386"
      - arm64
    ignore:
      - goos: darwin
        goarch: "386"
archives:
  - files:
      - README.md
      - LICENSE
    replacements:
      darwin: MacOS
      linux: Linux
      windows: Windows
      386: x86_32
      amd64: x86_64
      arm64: Arm64
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
