before:
  hooks:
    - go mod tidy
builds:
  - id: sender
    main: ./cmd/sender/main.go
    binary: sender
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
  - id: receiver
    main: ./cmd/receiver/main.go
    binary: receiver
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: darwin
  - id: sendfiles
    main: ./cmd/sendfiles/main.go
    binary: sendfiles
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: darwin
  - id: watcher
    main: ./cmd/watcher/main.go
    binary: watcher
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
    goarch:
      - amd64
      - arm64
  - id: watcher-mac
    main: ./cmd/watcher/main.go
    binary: watcher
    env:
      - CGO_ENABLED=1
    goos:
      - darwin
    goarch:
      - amd64
      - arm64
archives:
  - files:
      - README.md
      - LICENSE
    rlcp: true
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else }}{{ .Arch }}{{ end }}
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ incpatch .Version }}"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
