name: Build

on:
  push:
    paths: ["**.go", "go.mod", ".github/workflows/*"]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        go:
          - "1.19"
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go }}

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v3
        with:
          version: latest
          args: release --snapshot --rm-dist
