name: Build

on:
  push:
    paths: ["**.go", "go.mod", ".github/workflows/*"]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        go: ["1.19"]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go }}

      - name: build
        run: |
          GOOS=darwin GOARCH=amd64 go build ./cmd/...
          GOOS=darwin GOARCH=arm64 go build ./cmd/...
          GOOS=linux GOARCH=386 go build ./cmd/...
          GOOS=linux GOARCH=amd64 go build ./cmd/...
          GOOS=linux GOARCH=arm go build ./cmd/...
          GOOS=linux GOARCH=arm64 go build ./cmd/...
          GOOS=linux GOARCH=loong64 go build ./cmd/...
          GOOS=linux GOARCH=mips go build ./cmd/...
          GOOS=linux GOARCH=mips64 go build ./cmd/...
          GOOS=linux GOARCH=mips64le go build ./cmd/...
          GOOS=linux GOARCH=mipsle go build ./cmd/...
          GOOS=linux GOARCH=ppc64 go build ./cmd/...
          GOOS=linux GOARCH=ppc64le go build ./cmd/...
          GOOS=linux GOARCH=riscv64 go build ./cmd/...
          GOOS=linux GOARCH=s390x go build ./cmd/...
          GOOS=windows GOARCH=386 go build ./cmd/...
          GOOS=windows GOARCH=amd64 go build ./cmd/...
          GOOS=windows GOARCH=arm go build ./cmd/...
          GOOS=windows GOARCH=arm64 go build ./cmd/...
