name: Go

on:
  push:
    paths: ["**.go", "go.mod", ".github/workflows/*"]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        go: ["1.15", "1.16", "1.17", "1.18", "1.19"]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go }}

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...
