name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
<<<<<<< HEAD
=======

>>>>>>> main
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
<<<<<<< HEAD
        go-version: 1.19
=======
        go-version: 1.18
>>>>>>> main

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
