name: Lint
on:
  push:
    paths: ["**.go", "go.mod", ".github/workflows/*"]

jobs:
  lint:
    name: "lint"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        go:
          - "1.19"
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: setup Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go }}

      - name: Run linters
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest

      - name: Go vet
        run: "go vet ./..."

      - name: Staticcheck
        uses: dominikh/staticcheck-action@master
        with:
          version: "2022.1"
          install-go: false
          cache-key: ${{ matrix.go }}
