name: Staticcheck
on:
  push:
    paths: ["**.go", "go.mod", ".github/workflows/*"]

jobs:
  staticcheck:
    name: "staticcheck"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        go:
          - "1.19"
    steps:
      - name: setup Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go }}

      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - run: "go vet ./..."
      - uses: dominikh/staticcheck-action@v1.2.0
        with:
          version: "2022.1"
